[package]
name = "crow-agentd"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
base64.workspace = true
clap.workspace = true
crow-agent-core = { version = "=0.1.15", path = "../../crates/crow-agent-core" }
crow-agent-protocol = { version = "=0.1.15", path = "../../crates/crow-agent-protocol" }
futures-util.workspace = true
hex.workspace = true
interprocess.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
time.workspace = true
tokio.workspace = true
tokio-tungstenite.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
url.workspace = true
uuid.workspace = true
zeroize.workspace = true

[dev-dependencies]
tempfile = "3.23.0"

[lints]
workspace = true
